"""admin info

Revision ID: c486071c07c6
Revises: 984b8755c402
Create Date: 2024-01-06 18:37:00.777653

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c486071c07c6'
down_revision = '984b8755c402'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('password', sa.String(length=120), nullable=False))
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('role_level',
               existing_type=mysql.VARCHAR(length=40),
               nullable=True)
        batch_op.alter_column('skills',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('skills',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('role_level',
               existing_type=mysql.VARCHAR(length=40),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
        batch_op.drop_column('password')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
